name: Secure CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:

      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Semgrep
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      - name: Crear carpeta de reportes
        run: mkdir -p reports

      - name: Ejecutar Semgrep
        run: |
          semgrep scan --config auto --json --output reports/semgrep-report.json . || true

      - name: Instalar Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y

      - name: Ejecutar escaneo con Trivy
        run: |
          trivy fs . > reports/trivy-report.txt || true

      - name: Subir reportes
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: reports/
